services:
  - type: web
    runtime: node
    name: nestjs-app
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: DATABASE_URL
        value: your_render_database_url